#=============================================================================
# time_tagger.xdc
# Xilinx Design Constraints for FPGA Time Tagger on ZCU216 (XCZU49DR)
#=============================================================================
# NOTE: Pin assignments use placeholder locations for the ZCU216 evaluation
# board. Users MUST customize pin LOC and IOSTANDARD values to match their
# specific board revision and FMC/connector pinout.
#=============================================================================

#=============================================================================
# Section 1: Primary Clock Definitions
#=============================================================================

# On-board reference clock (100 MHz differential, from ZCU216 Si570 oscillator)
# Adjust LOC to match actual board clock input pins
set_property PACKAGE_PIN AJ6 [get_ports clk_board]
set_property IOSTANDARD LVDS [get_ports clk_board]
create_clock -period 10.000 -name clk_board [get_ports clk_board]

# External 10 MHz reference clock input (from QKD equipment)
# Validates: Requirement 7.1
set_property PACKAGE_PIN AK17 [get_ports clk_ext_10mhz]
set_property IOSTANDARD LVCMOS18 [get_ports clk_ext_10mhz]
create_clock -period 100.000 -name clk_ext_10mhz [get_ports clk_ext_10mhz]

#=============================================================================
# Section 2: Generated Clock Definitions
#=============================================================================
# These clocks are generated by the MMCM/PLL in clock_manager.
# Validates: Requirement 7.3 (500 MHz ± 50 ppm coarse clock)

# 500 MHz coarse clock (2 ns period) - TDC sampling and coarse counter
create_generated_clock -name clk_coarse \
    -source [get_pins u_clock_manager/mmcm_inst/CLKIN1] \
    -multiply_by 5 -divide_by 1 \
    [get_pins u_clock_manager/mmcm_inst/CLKOUT0]

# 250 MHz AXI clock (4 ns period) - AXI4-Lite register interface
create_generated_clock -name clk_axi \
    -source [get_pins u_clock_manager/mmcm_inst/CLKIN1] \
    -multiply_by 5 -divide_by 2 \
    [get_pins u_clock_manager/mmcm_inst/CLKOUT1]

# 250 MHz DMA clock (4 ns period) - AXI DMA data path
create_generated_clock -name clk_dma \
    -source [get_pins u_clock_manager/mmcm_inst/CLKIN1] \
    -multiply_by 5 -divide_by 2 \
    [get_pins u_clock_manager/mmcm_inst/CLKOUT2]

# 100 MHz calibration clock (10 ns period) - Calibration module
create_generated_clock -name clk_cal \
    -source [get_pins u_clock_manager/mmcm_inst/CLKIN1] \
    -multiply_by 1 -divide_by 1 \
    [get_pins u_clock_manager/mmcm_inst/CLKOUT3]

#=============================================================================
# Section 3: Input Channel Pin Assignments (8 channels, LVDS)
#=============================================================================
# Event input channels - LVDS differential pairs on FMC HPC connector
# Users MUST update LOC values to match their FMC pinout and bank assignment.
# These placeholders assume Bank 64 (HP I/O, 1.8V VCCO).

# Channel 0
set_property PACKAGE_PIN A10 [get_ports {event_in[0]}]
set_property IOSTANDARD LVDS [get_ports {event_in[0]}]

# Channel 1
set_property PACKAGE_PIN B9  [get_ports {event_in[1]}]
set_property IOSTANDARD LVDS [get_ports {event_in[1]}]

# Channel 2
set_property PACKAGE_PIN C11 [get_ports {event_in[2]}]
set_property IOSTANDARD LVDS [get_ports {event_in[2]}]

# Channel 3
set_property PACKAGE_PIN D10 [get_ports {event_in[3]}]
set_property IOSTANDARD LVDS [get_ports {event_in[3]}]

# Channel 4
set_property PACKAGE_PIN E12 [get_ports {event_in[4]}]
set_property IOSTANDARD LVDS [get_ports {event_in[4]}]

# Channel 5
set_property PACKAGE_PIN F11 [get_ports {event_in[5]}]
set_property IOSTANDARD LVDS [get_ports {event_in[5]}]

# Channel 6
set_property PACKAGE_PIN G10 [get_ports {event_in[6]}]
set_property IOSTANDARD LVDS [get_ports {event_in[6]}]

# Channel 7
set_property PACKAGE_PIN H9  [get_ports {event_in[7]}]
set_property IOSTANDARD LVDS [get_ports {event_in[7]}]

#=============================================================================
# Section 4: Control Signal Pin Assignments (LVCMOS18)
#=============================================================================

# External sync pulse input
set_property PACKAGE_PIN AL17 [get_ports sync_pulse]
set_property IOSTANDARD LVCMOS18 [get_ports sync_pulse]

# External clock valid indicator
set_property PACKAGE_PIN AM17 [get_ports ext_clk_valid]
set_property IOSTANDARD LVCMOS18 [get_ports ext_clk_valid]

# Active-low system reset
set_property PACKAGE_PIN AN17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]

# Status outputs (active-high)
set_property PACKAGE_PIN AP18 [get_ports locked]
set_property IOSTANDARD LVCMOS18 [get_ports locked]

set_property PACKAGE_PIN AR18 [get_ports clk_loss_error]
set_property IOSTANDARD LVCMOS18 [get_ports clk_loss_error]

set_property PACKAGE_PIN AT18 [get_ports cal_busy]
set_property IOSTANDARD LVCMOS18 [get_ports cal_busy]

set_property PACKAGE_PIN AU19 [get_ports {overflow_flags[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[0]}]
set_property PACKAGE_PIN AV19 [get_ports {overflow_flags[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[1]}]
set_property PACKAGE_PIN AW19 [get_ports {overflow_flags[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[2]}]
set_property PACKAGE_PIN AY19 [get_ports {overflow_flags[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[3]}]
set_property PACKAGE_PIN BA20 [get_ports {overflow_flags[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[4]}]
set_property PACKAGE_PIN BB20 [get_ports {overflow_flags[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[5]}]
set_property PACKAGE_PIN BC20 [get_ports {overflow_flags[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[6]}]
set_property PACKAGE_PIN BD20 [get_ports {overflow_flags[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {overflow_flags[7]}]

#=============================================================================
# Section 5: Input Delay Constraints
#=============================================================================
# Input delay constraints for event channels relative to clk_coarse.
# These account for board trace delay and input buffer delay.
# Values are estimates; adjust based on board-level timing analysis.

set_input_delay -clock clk_coarse -max 0.500 [get_ports {event_in[*]}]
set_input_delay -clock clk_coarse -min 0.100 [get_ports {event_in[*]}]

set_input_delay -clock clk_coarse -max 0.500 [get_ports sync_pulse]
set_input_delay -clock clk_coarse -min 0.100 [get_ports sync_pulse]

set_input_delay -clock clk_ext_10mhz -max 2.000 [get_ports ext_clk_valid]
set_input_delay -clock clk_ext_10mhz -min 0.500 [get_ports ext_clk_valid]

#=============================================================================
# Section 6: False Path Constraints for Clock Domain Crossings
#=============================================================================
# All CDC paths use dual-register synchronizers (for single-bit signals) or
# gray-code async FIFOs (for multi-bit data). These paths are safe to exclude
# from timing analysis between unrelated clock domains.

# False paths between clk_coarse (500 MHz) and clk_dma (250 MHz)
# Tag FIFO gray-code pointer crossings
set_false_path -from [get_clocks clk_coarse] -to [get_clocks clk_dma]
set_false_path -from [get_clocks clk_dma] -to [get_clocks clk_coarse]

# False paths between clk_coarse (500 MHz) and clk_axi (250 MHz)
# Configuration register CDC synchronizers
set_false_path -from [get_clocks clk_coarse] -to [get_clocks clk_axi]
set_false_path -from [get_clocks clk_axi] -to [get_clocks clk_coarse]

# False paths between clk_coarse (500 MHz) and clk_cal (100 MHz)
# Calibration LUT write and temperature monitoring CDC
set_false_path -from [get_clocks clk_coarse] -to [get_clocks clk_cal]
set_false_path -from [get_clocks clk_cal] -to [get_clocks clk_coarse]

# False paths between clk_axi (250 MHz) and clk_cal (100 MHz)
# Calibration status register CDC
set_false_path -from [get_clocks clk_axi] -to [get_clocks clk_cal]
set_false_path -from [get_clocks clk_cal] -to [get_clocks clk_axi]

# False paths between clk_dma (250 MHz) and clk_axi (250 MHz)
# DMA status to register file CDC
set_false_path -from [get_clocks clk_dma] -to [get_clocks clk_axi]
set_false_path -from [get_clocks clk_axi] -to [get_clocks clk_dma]

# External 10 MHz reference to internal clocks (async relationship)
set_false_path -from [get_clocks clk_ext_10mhz] -to [get_clocks clk_coarse]
set_false_path -from [get_clocks clk_ext_10mhz] -to [get_clocks clk_axi]
set_false_path -from [get_clocks clk_ext_10mhz] -to [get_clocks clk_dma]
set_false_path -from [get_clocks clk_ext_10mhz] -to [get_clocks clk_cal]

#=============================================================================
# Section 7: Max Delay Constraints for CDC Synchronizer Paths
#=============================================================================
# Even though false paths are set above, we add max_delay constraints on the
# synchronizer first-stage flip-flops to ensure they are placed close together
# and meet the MTBF requirements for metastability resolution.

# Sync pulse synchronizer (clk_board domain -> clk_coarse domain)
set_max_delay -datapath_only -from [get_ports sync_pulse] \
    -to [get_cells -hierarchical -filter {NAME =~ *sync_pulse_sync_reg[0]*}] 2.000

# FIFO gray-code pointer synchronizers (clk_coarse -> clk_dma)
set_max_delay -datapath_only \
    -from [get_cells -hierarchical -filter {NAME =~ *gen_tag_fifo*wr_ptr_gray_reg*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *gen_tag_fifo*wr_ptr_sync_reg[0]*}] 4.000

# FIFO gray-code pointer synchronizers (clk_dma -> clk_coarse)
set_max_delay -datapath_only \
    -from [get_cells -hierarchical -filter {NAME =~ *gen_tag_fifo*rd_ptr_gray_reg*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *gen_tag_fifo*rd_ptr_sync_reg[0]*}] 2.000

# Calibration LUT write synchronizer (clk_cal -> clk_coarse)
set_max_delay -datapath_only \
    -from [get_cells -hierarchical -filter {NAME =~ *u_calibration_module*cal_lut_wr_reg*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *gen_tdc_channel*cal_lut_wr_sync_reg[0]*}] 2.000

# Configuration register synchronizers (clk_axi -> clk_coarse)
set_max_delay -datapath_only \
    -from [get_cells -hierarchical -filter {NAME =~ *u_axi_register_file*cfg_*_reg*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *cfg_*_sync_reg[0]*}] 2.000

#=============================================================================
# Section 8: CARRY8 Placement Constraints for Fine Interpolator Delay Lines
#=============================================================================
# Deterministic routing of the CARRY8 delay chains is critical for consistent
# TDC resolution across builds. Each channel's 32 CARRY8 cells are placed in
# a contiguous vertical column within a single clock region.
#
# The LOC constraints ensure:
#   1. All CARRY8 cells in a channel are in the same column (deterministic delay)
#   2. Channels are spread across different columns to avoid routing congestion
#   3. Placement is within a single clock region for minimal clock skew
#
# Adjust SLICE locations based on actual device floorplan and available resources.
# Format: SLICE_X{col}Y{row} - each CARRY8 occupies one SLICE vertically.

# Channel 0: Column X50, starting at Y0 (32 CARRY8 cells = 32 SLICEs)
set_property LOC SLICE_X50Y0  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X50Y1  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X50Y2  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X50Y3  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X50Y4  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X50Y5  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X50Y6  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X50Y7  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X50Y8  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X50Y9  [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X50Y10 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X50Y11 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X50Y12 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X50Y13 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X50Y14 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X50Y15 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X50Y16 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X50Y17 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X50Y18 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X50Y19 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X50Y20 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X50Y21 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X50Y22 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X50Y23 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X50Y24 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X50Y25 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X50Y26 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X50Y27 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X50Y28 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X50Y29 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X50Y30 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X50Y31 [get_cells gen_tdc_channel[0].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 1: Column X52, starting at Y0
set_property LOC SLICE_X52Y0  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X52Y1  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X52Y2  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X52Y3  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X52Y4  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X52Y5  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X52Y6  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X52Y7  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X52Y8  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X52Y9  [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X52Y10 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X52Y11 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X52Y12 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X52Y13 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X52Y14 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X52Y15 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X52Y16 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X52Y17 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X52Y18 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X52Y19 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X52Y20 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X52Y21 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X52Y22 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X52Y23 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X52Y24 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X52Y25 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X52Y26 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X52Y27 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X52Y28 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X52Y29 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X52Y30 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X52Y31 [get_cells gen_tdc_channel[1].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 2: Column X54, starting at Y0
set_property LOC SLICE_X54Y0  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X54Y1  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X54Y2  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X54Y3  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X54Y4  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X54Y5  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X54Y6  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X54Y7  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X54Y8  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X54Y9  [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X54Y10 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X54Y11 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X54Y12 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X54Y13 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X54Y14 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X54Y15 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X54Y16 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X54Y17 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X54Y18 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X54Y19 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X54Y20 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X54Y21 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X54Y22 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X54Y23 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X54Y24 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X54Y25 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X54Y26 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X54Y27 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X54Y28 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X54Y29 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X54Y30 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X54Y31 [get_cells gen_tdc_channel[2].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 3: Column X56, starting at Y0
set_property LOC SLICE_X56Y0  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X56Y1  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X56Y2  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X56Y3  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X56Y4  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X56Y5  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X56Y6  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X56Y7  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X56Y8  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X56Y9  [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X56Y10 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X56Y11 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X56Y12 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X56Y13 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X56Y14 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X56Y15 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X56Y16 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X56Y17 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X56Y18 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X56Y19 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X56Y20 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X56Y21 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X56Y22 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X56Y23 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X56Y24 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X56Y25 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X56Y26 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X56Y27 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X56Y28 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X56Y29 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X56Y30 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X56Y31 [get_cells gen_tdc_channel[3].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 4: Column X58, starting at Y0
set_property LOC SLICE_X58Y0  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X58Y1  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X58Y2  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X58Y3  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X58Y4  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X58Y5  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X58Y6  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X58Y7  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X58Y8  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X58Y9  [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X58Y10 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X58Y11 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X58Y12 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X58Y13 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X58Y14 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X58Y15 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X58Y16 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X58Y17 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X58Y18 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X58Y19 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X58Y20 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X58Y21 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X58Y22 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X58Y23 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X58Y24 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X58Y25 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X58Y26 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X58Y27 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X58Y28 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X58Y29 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X58Y30 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X58Y31 [get_cells gen_tdc_channel[4].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 5: Column X60, starting at Y0
set_property LOC SLICE_X60Y0  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X60Y1  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X60Y2  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X60Y3  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X60Y4  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X60Y5  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X60Y6  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X60Y7  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X60Y8  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X60Y9  [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X60Y10 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X60Y11 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X60Y12 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X60Y13 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X60Y14 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X60Y15 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X60Y16 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X60Y17 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X60Y18 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X60Y19 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X60Y20 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X60Y21 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X60Y22 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X60Y23 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X60Y24 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X60Y25 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X60Y26 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X60Y27 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X60Y28 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X60Y29 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X60Y30 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X60Y31 [get_cells gen_tdc_channel[5].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 6: Column X62, starting at Y0
set_property LOC SLICE_X62Y0  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X62Y1  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X62Y2  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X62Y3  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X62Y4  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X62Y5  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X62Y6  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X62Y7  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X62Y8  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X62Y9  [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X62Y10 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X62Y11 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X62Y12 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X62Y13 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X62Y14 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X62Y15 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X62Y16 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X62Y17 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X62Y18 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X62Y19 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X62Y20 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X62Y21 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X62Y22 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X62Y23 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X62Y24 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X62Y25 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X62Y26 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X62Y27 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X62Y28 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X62Y29 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X62Y30 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X62Y31 [get_cells gen_tdc_channel[6].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

# Channel 7: Column X64, starting at Y0
set_property LOC SLICE_X64Y0  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[0].carry8_inst]
set_property LOC SLICE_X64Y1  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[1].carry8_inst]
set_property LOC SLICE_X64Y2  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[2].carry8_inst]
set_property LOC SLICE_X64Y3  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[3].carry8_inst]
set_property LOC SLICE_X64Y4  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[4].carry8_inst]
set_property LOC SLICE_X64Y5  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[5].carry8_inst]
set_property LOC SLICE_X64Y6  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[6].carry8_inst]
set_property LOC SLICE_X64Y7  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[7].carry8_inst]
set_property LOC SLICE_X64Y8  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[8].carry8_inst]
set_property LOC SLICE_X64Y9  [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[9].carry8_inst]
set_property LOC SLICE_X64Y10 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[10].carry8_inst]
set_property LOC SLICE_X64Y11 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[11].carry8_inst]
set_property LOC SLICE_X64Y12 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[12].carry8_inst]
set_property LOC SLICE_X64Y13 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[13].carry8_inst]
set_property LOC SLICE_X64Y14 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[14].carry8_inst]
set_property LOC SLICE_X64Y15 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[15].carry8_inst]
set_property LOC SLICE_X64Y16 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[16].carry8_inst]
set_property LOC SLICE_X64Y17 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[17].carry8_inst]
set_property LOC SLICE_X64Y18 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[18].carry8_inst]
set_property LOC SLICE_X64Y19 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[19].carry8_inst]
set_property LOC SLICE_X64Y20 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[20].carry8_inst]
set_property LOC SLICE_X64Y21 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[21].carry8_inst]
set_property LOC SLICE_X64Y22 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[22].carry8_inst]
set_property LOC SLICE_X64Y23 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[23].carry8_inst]
set_property LOC SLICE_X64Y24 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[24].carry8_inst]
set_property LOC SLICE_X64Y25 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[25].carry8_inst]
set_property LOC SLICE_X64Y26 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[26].carry8_inst]
set_property LOC SLICE_X64Y27 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[27].carry8_inst]
set_property LOC SLICE_X64Y28 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[28].carry8_inst]
set_property LOC SLICE_X64Y29 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[29].carry8_inst]
set_property LOC SLICE_X64Y30 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[30].carry8_inst]
set_property LOC SLICE_X64Y31 [get_cells gen_tdc_channel[7].u_tdc_channel/u_fine_interp/gen_carry8[31].carry8_inst]

#=============================================================================
# Section 9: DONT_TOUCH and Routing Constraints for Delay Lines
#=============================================================================
# Prevent optimization of the CARRY8 chain and ensure the tools do not
# reroute the carry chain connections.

set_property DONT_TOUCH TRUE [get_cells -hierarchical -filter {NAME =~ *gen_carry8*carry8_inst}]

# Prohibit routing optimization on carry chain nets
set_property IS_ROUTE_FIXED TRUE [get_nets -hierarchical -filter {NAME =~ *gen_carry8*carry_chain*}] -quiet

#=============================================================================
# Section 10: Timing Exceptions for Delay Line Sampling
#=============================================================================
# The CARRY8 delay line is an asynchronous path by nature (event_in propagates
# through combinational carry logic). The sampling flip-flops capture the
# thermometer code on the clock edge. This is intentionally metastable at the
# transition boundary - the bubble correction logic handles this.

# Set multicycle path for the pipeline register stage (bubble correction input)
set_multicycle_path 2 -setup \
    -from [get_cells -hierarchical -filter {NAME =~ *gen_carry8*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *sample_reg*}]

set_multicycle_path 1 -hold \
    -from [get_cells -hierarchical -filter {NAME =~ *gen_carry8*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *sample_reg*}]

#=============================================================================
# Section 11: Miscellaneous Constraints
#=============================================================================

# Target device
set_property PART xczu49dr-ffvf1760-2-e [current_project] -quiet

# Bitstream configuration
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design] -quiet
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design] -quiet

# Configuration voltage
set_property CONFIG_VOLTAGE 1.8 [current_design] -quiet
set_property CFGBVS GND [current_design] -quiet

#=============================================================================
# End of constraints file
#=============================================================================
